PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "PIICHI: …Moolo.\n"
    .string "Pasaali oyhan iisafon\l"
    .string "wisahkahchommo. TVkafon hoonkati.\p"
    .string "Oow, ey. PROF. BAYA,\n" 
    .string "komayakhachokkooli chiwihliiyok\l"
    .string "wiikasti.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "PIICHI: …Moolo.\n"
    .string "All girls dream of traveling.\l"
    .string "TVkafon hoonkati.\p"
    .string "Oow, ey. PROF. BAYA, komayakhachokkòoli\n"
    .string "chiwihliiyok wiikasti.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "PIICHI: {PLAYER}!\n"
    .string "You should take a quick rest.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "PIICHI: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "There's a movie on TV.\n"
    .string "Four boys are walking on railroad\l"
    .string "tracks.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "There's a movie on TV.\n"
    .string "A girl with her hair in pigtails is\l"
    .string "walking up a brick road.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

